<?php

/**
 * BaseRolePrincipal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $role_id
 * @property integer $principal_id
 * @property timestamp $expiration
 * @property Role $Role
 * @property Principal $Principal
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method integer       getRoleId()       Returns the current record's "role_id" value
 * @method integer       getPrincipalId()  Returns the current record's "principal_id" value
 * @method timestamp     getExpiration()   Returns the current record's "expiration" value
 * @method Role          getRole()         Returns the current record's "Role" value
 * @method Principal     getPrincipal()    Returns the current record's "Principal" value
 * @method RolePrincipal setId()           Sets the current record's "id" value
 * @method RolePrincipal setRoleId()       Sets the current record's "role_id" value
 * @method RolePrincipal setPrincipalId()  Sets the current record's "principal_id" value
 * @method RolePrincipal setExpiration()   Sets the current record's "expiration" value
 * @method RolePrincipal setRole()         Sets the current record's "Role" value
 * @method RolePrincipal setPrincipal()    Sets the current record's "Principal" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     gyufi@sztaki.hu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRolePrincipal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('role_principal');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('principal_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('expiration', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Role', array(
             'local' => 'role_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Principal', array(
             'local' => 'principal_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}