<?php

/**
 * BaseOrganizationEntitlementPack
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $organization_id
 * @property integer $entitlement_pack_id
 * @property enum $status
 * @property timestamp $created_at
 * @property timestamp $accept_at
 * @property Organization $Organization
 * @property EntitlementPack $EntitlementPack
 * 
 * @method integer                     getId()                  Returns the current record's "id" value
 * @method integer                     getOrganizationId()      Returns the current record's "organization_id" value
 * @method integer                     getEntitlementPackId()   Returns the current record's "entitlement_pack_id" value
 * @method enum                        getStatus()              Returns the current record's "status" value
 * @method timestamp                   getCreatedAt()           Returns the current record's "created_at" value
 * @method timestamp                   getAcceptAt()            Returns the current record's "accept_at" value
 * @method Organization                getOrganization()        Returns the current record's "Organization" value
 * @method EntitlementPack             getEntitlementPack()     Returns the current record's "EntitlementPack" value
 * @method OrganizationEntitlementPack setId()                  Sets the current record's "id" value
 * @method OrganizationEntitlementPack setOrganizationId()      Sets the current record's "organization_id" value
 * @method OrganizationEntitlementPack setEntitlementPackId()   Sets the current record's "entitlement_pack_id" value
 * @method OrganizationEntitlementPack setStatus()              Sets the current record's "status" value
 * @method OrganizationEntitlementPack setCreatedAt()           Sets the current record's "created_at" value
 * @method OrganizationEntitlementPack setAcceptAt()            Sets the current record's "accept_at" value
 * @method OrganizationEntitlementPack setOrganization()        Sets the current record's "Organization" value
 * @method OrganizationEntitlementPack setEntitlementPack()     Sets the current record's "EntitlementPack" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     gyufi@sztaki.hu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrganizationEntitlementPack extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('organization_entitlement_pack');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('organization_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('entitlement_pack_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'pending',
              1 => 'accepted',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('accept_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organization', array(
             'local' => 'organization_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('EntitlementPack', array(
             'local' => 'entitlement_pack_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}