<?php

/**
 * BaseEntitlementPackEntitlement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entitlement_pack_id
 * @property integer $entitlement_id
 * @property EntitlementPack $EntitlementPack
 * @property Entitlement $Entitlement
 * 
 * @method integer                    getId()                  Returns the current record's "id" value
 * @method integer                    getEntitlementPackId()   Returns the current record's "entitlement_pack_id" value
 * @method integer                    getEntitlementId()       Returns the current record's "entitlement_id" value
 * @method EntitlementPack            getEntitlementPack()     Returns the current record's "EntitlementPack" value
 * @method Entitlement                getEntitlement()         Returns the current record's "Entitlement" value
 * @method EntitlementPackEntitlement setId()                  Sets the current record's "id" value
 * @method EntitlementPackEntitlement setEntitlementPackId()   Sets the current record's "entitlement_pack_id" value
 * @method EntitlementPackEntitlement setEntitlementId()       Sets the current record's "entitlement_id" value
 * @method EntitlementPackEntitlement setEntitlementPack()     Sets the current record's "EntitlementPack" value
 * @method EntitlementPackEntitlement setEntitlement()         Sets the current record's "Entitlement" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     gyufi@sztaki.hu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEntitlementPackEntitlement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entitlement_pack_entitlement');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('entitlement_pack_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('entitlement_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EntitlementPack', array(
             'local' => 'entitlement_pack_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Entitlement', array(
             'local' => 'entitlement_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}