<?php

/**
 * BaseEntitlementPack
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $service_id
 * @property integer $showorder
 * @property text $description
 * @property timestamp $created_at
 * @property enum $type
 * @property text $token
 * @property Service $Service
 * @property Doctrine_Collection $Entitlement
 * @property Doctrine_Collection $OrganizationEntitlementPack
 * @property Doctrine_Collection $EntitlementPackEntitlement
 * 
 * @method integer             getId()                          Returns the current record's "id" value
 * @method string              getName()                        Returns the current record's "name" value
 * @method integer             getServiceId()                   Returns the current record's "service_id" value
 * @method integer             getShoworder()                   Returns the current record's "showorder" value
 * @method text                getDescription()                 Returns the current record's "description" value
 * @method timestamp           getCreatedAt()                   Returns the current record's "created_at" value
 * @method enum                getType()                        Returns the current record's "type" value
 * @method text                getToken()                       Returns the current record's "token" value
 * @method Service             getService()                     Returns the current record's "Service" value
 * @method Doctrine_Collection getEntitlement()                 Returns the current record's "Entitlement" collection
 * @method Doctrine_Collection getOrganizationEntitlementPack() Returns the current record's "OrganizationEntitlementPack" collection
 * @method Doctrine_Collection getEntitlementPackEntitlement()  Returns the current record's "EntitlementPackEntitlement" collection
 * @method EntitlementPack     setId()                          Sets the current record's "id" value
 * @method EntitlementPack     setName()                        Sets the current record's "name" value
 * @method EntitlementPack     setServiceId()                   Sets the current record's "service_id" value
 * @method EntitlementPack     setShoworder()                   Sets the current record's "showorder" value
 * @method EntitlementPack     setDescription()                 Sets the current record's "description" value
 * @method EntitlementPack     setCreatedAt()                   Sets the current record's "created_at" value
 * @method EntitlementPack     setType()                        Sets the current record's "type" value
 * @method EntitlementPack     setToken()                       Sets the current record's "token" value
 * @method EntitlementPack     setService()                     Sets the current record's "Service" value
 * @method EntitlementPack     setEntitlement()                 Sets the current record's "Entitlement" collection
 * @method EntitlementPack     setOrganizationEntitlementPack() Sets the current record's "OrganizationEntitlementPack" collection
 * @method EntitlementPack     setEntitlementPackEntitlement()  Sets the current record's "EntitlementPackEntitlement" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     gyufi@sztaki.hu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEntitlementPack extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('entitlement_pack');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('service_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('showorder', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'test',
              1 => 'hidden',
              2 => 'browseable',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('token', 'text', null, array(
             'type' => 'text',
             ));

        $this->option('orderBy', 'showorder');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Service', array(
             'local' => 'service_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Entitlement', array(
             'refClass' => 'EntitlementPackEntitlement',
             'local' => 'entitlement_pack_id',
             'foreign' => 'entitlement_id'));

        $this->hasMany('OrganizationEntitlementPack', array(
             'local' => 'id',
             'foreign' => 'entitlement_pack_id'));

        $this->hasMany('EntitlementPackEntitlement', array(
             'local' => 'id',
             'foreign' => 'entitlement_pack_id'));
    }
}