<?php

/**
 * BaseOrganizationService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $organization_id
 * @property integer $service_id
 * @property enum $status
 * @property timestamp $created_at
 * @property timestamp $accept_at
 * @property Organization $Organization
 * @property Service $Service
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getOrganizationId()  Returns the current record's "organization_id" value
 * @method integer             getServiceId()       Returns the current record's "service_id" value
 * @method enum                getStatus()          Returns the current record's "status" value
 * @method timestamp           getCreatedAt()       Returns the current record's "created_at" value
 * @method timestamp           getAcceptAt()        Returns the current record's "accept_at" value
 * @method Organization        getOrganization()    Returns the current record's "Organization" value
 * @method Service             getService()         Returns the current record's "Service" value
 * @method OrganizationService setId()              Sets the current record's "id" value
 * @method OrganizationService setOrganizationId()  Sets the current record's "organization_id" value
 * @method OrganizationService setServiceId()       Sets the current record's "service_id" value
 * @method OrganizationService setStatus()          Sets the current record's "status" value
 * @method OrganizationService setCreatedAt()       Sets the current record's "created_at" value
 * @method OrganizationService setAcceptAt()        Sets the current record's "accept_at" value
 * @method OrganizationService setOrganization()    Sets the current record's "Organization" value
 * @method OrganizationService setService()         Sets the current record's "Service" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     gyufi@sztaki.hu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrganizationService extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('organization_service');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('organization_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('service_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'pending',
              1 => 'accepted',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('accept_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organization', array(
             'local' => 'organization_id',
             'foreign' => 'id'));

        $this->hasOne('Service', array(
             'local' => 'service_id',
             'foreign' => 'id'));
    }
}