<?php

/**
 * BaseRoleEntitlementPack
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $role_id
 * @property integer $entitlement_pack_id
 * @property Role $Role
 * @property EntitlementPack $EntitlementPack
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method integer             getRoleId()              Returns the current record's "role_id" value
 * @method integer             getEntitlementPackId()   Returns the current record's "entitlement_pack_id" value
 * @method Role                getRole()                Returns the current record's "Role" value
 * @method EntitlementPack     getEntitlementPack()     Returns the current record's "EntitlementPack" value
 * @method RoleEntitlementPack setId()                  Sets the current record's "id" value
 * @method RoleEntitlementPack setRoleId()              Sets the current record's "role_id" value
 * @method RoleEntitlementPack setEntitlementPackId()   Sets the current record's "entitlement_pack_id" value
 * @method RoleEntitlementPack setRole()                Sets the current record's "Role" value
 * @method RoleEntitlementPack setEntitlementPack()     Sets the current record's "EntitlementPack" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     gyufi@sztaki.hu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoleEntitlementPack extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('role_entitlement_pack');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('entitlement_pack_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Role', array(
             'local' => 'role_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('EntitlementPack', array(
             'local' => 'entitlement_pack_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}