<?php

/**
 * BaseOrganizationPrincipal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $organization_id
 * @property integer $principal_id
 * @property Organization $Organization
 * @property Principal $Principal
 * 
 * @method integer               getId()              Returns the current record's "id" value
 * @method integer               getOrganizationId()  Returns the current record's "organization_id" value
 * @method integer               getPrincipalId()     Returns the current record's "principal_id" value
 * @method Organization          getOrganization()    Returns the current record's "Organization" value
 * @method Principal             getPrincipal()       Returns the current record's "Principal" value
 * @method OrganizationPrincipal setId()              Sets the current record's "id" value
 * @method OrganizationPrincipal setOrganizationId()  Sets the current record's "organization_id" value
 * @method OrganizationPrincipal setPrincipalId()     Sets the current record's "principal_id" value
 * @method OrganizationPrincipal setOrganization()    Sets the current record's "Organization" value
 * @method OrganizationPrincipal setPrincipal()       Sets the current record's "Principal" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     gyufi@sztaki.hu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrganizationPrincipal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('organization_principal');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('organization_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('principal_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organization', array(
             'local' => 'organization_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Principal', array(
             'local' => 'principal_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}