<?php

/**
 * BaseRoleEntitlement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $role_id
 * @property integer $entitlement_id
 * @property Role $Role
 * @property Entitlement $Entitlement
 * 
 * @method integer         getId()             Returns the current record's "id" value
 * @method integer         getRoleId()         Returns the current record's "role_id" value
 * @method integer         getEntitlementId()  Returns the current record's "entitlement_id" value
 * @method Role            getRole()           Returns the current record's "Role" value
 * @method Entitlement     getEntitlement()    Returns the current record's "Entitlement" value
 * @method RoleEntitlement setId()             Sets the current record's "id" value
 * @method RoleEntitlement setRoleId()         Sets the current record's "role_id" value
 * @method RoleEntitlement setEntitlementId()  Sets the current record's "entitlement_id" value
 * @method RoleEntitlement setRole()           Sets the current record's "Role" value
 * @method RoleEntitlement setEntitlement()    Sets the current record's "Entitlement" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     gyufi@sztaki.hu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoleEntitlement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('role_entitlement');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('entitlement_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Role', array(
             'local' => 'role_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Entitlement', array(
             'local' => 'entitlement_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}