<?php

/**
 * EntitlementPackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntitlementPackTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EntitlementPackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EntitlementPack');
    }
}