<?php

/**
 * Invitation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     gyufi@sztaki.hu
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Invitation extends BaseInvitation
{
  public function isMy()
  {
    $p = Doctrine::getTable('Principal')->findOneByFedid(sfContext::getInstance()->getUser()->getUsername());
    if (! $p)
      return false;
    return ($this->getOwner() == $p->getId());     
  }
  public function getPrincipalName()
  {
    return $this->getPrincipal()->getName();
  }
}
