<?php

/**
 * OrganizationEntitlementPackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganizationEntitlementPackTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganizationEntitlementPackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrganizationEntitlementPack');
    }
}