<?php

/**
 * OrganizationServiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganizationServiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganizationServiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrganizationService');
    }
}