<?php

/**
 * PrincipalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrincipalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrincipalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Principal');
    }
}