<?php

/**
 * RolePrincipalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RolePrincipalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RolePrincipalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RolePrincipal');
    }
}