generator:
  class: sfDoctrineGenerator
  param:
    model_class:           OrganizationService
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          organization_service
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [id, Organization, Service, status, created_at, accept_at ]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
