<?php

/**
 * EntitlementPackEntitlementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntitlementPackEntitlementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EntitlementPackEntitlementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EntitlementPackEntitlement');
    }
}