<?php

/**
 * InvitationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvitationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvitationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Invitation');
    }
}