<?php

/**
 * OrganizationPrincipalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganizationPrincipalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganizationPrincipalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrganizationPrincipal');
    }
}