<?php

/**
 * Organization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Organization extends BaseOrganization
{
  public function isMy(){
    foreach ($this->getPrincipal() as $p){
      if (sfContext::getInstance()->getUser()->getUsername() == $p->getFedid()){
        return TRUE;
      }
    }
    return FALSE;
  }
  
  public function getRelatedPrincipal(){
    $ps = array();
    /*foreach ($this->getRole() as $r){
      foreach($r->getRolePrincipal() as $rp){
        $p = $rp->getPrincipal();
        $ps[$p->getId()] = $p;
      }
    }*/
    foreach($this->getInvitation() as $i)
    {
      if ($i and $i->getStatus() == 'accepted')
      {
        $ps[] = $i->getPrincipal();
      }
    }
    return $ps;
  }
 
  public function amIRelated(){
    foreach ($this->getRelatedPrincipal() as $p){
      if (sfContext::getInstance()->getUser()->getUsername() == $p->getFedid()){
        return TRUE;
      }
    }
    return FALSE;
  }

  public function amIManager(){
    foreach ($this->getPrincipal() as $p){
      if (sfContext::getInstance()->getUser()->getUsername() == $p->getFedid()){
        return TRUE;
      }
    }
    return FALSE;
  }
  
  public function getManagers(){
    $managers = Doctrine_Query::create()->from('Principal p')
				   ->leftJoin('p.OrganizationPrincipal op')
				   ->where('op.organization_id=?',$this->getId())
				   ->execute();
    
    return $managers;
  }
  
  public function getManagersEmailArray(){
    $managers = $this->getManagers();
    $mails = array();
    foreach($managers as $manager)
    {
      $mails[$manager->getEmail()]=$manager->getName();
    }
    return $mails;
  }

  public function hasPendingService(){
    foreach ($this->getOrganizationService() as $s){
      if ($s->getStatus() == "pending"){
        return TRUE;
      }
    }
    return FALSE;
  }
}
