<?php

/**
 * Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Role extends BaseRole
{
  public function __toString()
  {
    return $this->getOrganization()."::".$this->getName();
  }
  
  public function updateEntitlements($oid){
  $q = Doctrine_Query::create()
                        ->from('Entitlement e')
                        ->leftJoin('e.EntitlementPackEntitlement epe')
                        ->leftJoin('epe.EntitlementPack ep')
                        ->leftJoin('ep.OrganizationEntitlementPack oe')
                        ->where('oe.organization_id = ?', $oid)
                        ->andWhere('oe.status = ?', 'accepted')->execute();
      $roles = Doctrine_Query::create()->from('RoleEntitlement re')->leftJoin('re.Role r')->where('r.organization_id = ?', $oid)->execute();
      foreach($roles as $r){
        $torolni = true;
	foreach ($q as $qe){
	  if ($qe->getId() == $r->getEntitlementId()) { $torolni = false; }
	}
	if ($torolni) { $r->delete(); }
      }
  }
  
  public function getMembers(){
    $members = Doctrine_Query::create()->from('Principal p')
				   ->leftJoin('p.RolePrincipal rp')
				   ->where('rp.role_id=?',$this->getId())
				   ->execute();
    return $members;
  }
  
  public function getMembersEmailArray(){
    $emails = array();
    foreach($this->getMembers() as $member){
      $emails[$member->getEmail()] = $member->getName();
    }
    return $emails;
  }
}
