<?php

/**
 * RoleEntitlementPackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleEntitlementPackTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoleEntitlementPackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RoleEntitlementPack');
    }
}