<?php

/**
 * RoleEntitlementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleEntitlementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoleEntitlementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RoleEntitlement');
    }
}