<?php

/**
 * ServiceInvitationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceInvitationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceInvitationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiceInvitation');
    }
}