# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [style.css,organization.css,smoothness/jquery-ui-1.8.13.custom.css]

  javascripts:    [jquery-1.5.1.min.js,jquery-ui-1.8.13.custom.min.js, tinymce/jscripts/tiny_mce/tiny_mce.js]

  has_layout:     true
  layout:         layout
